run_session_params:
  file_path: "run_session.log"
  app_name: "agents"
  user_id: "default"

pinecone_memory_params:
  file_path: "pinecone_memory.log"
  embedding_model: "all-MiniLM-L6-v2"

postgre_memory_db:
  file_path: "postgre_database.log"

prompt_loader:
  file_path: "prompt_loader.log"


bitemate_tools:
  file_path: "bitemate_tools.log"

meal_planner_agent:
  file_path: "meal_planner_agent.log"
  model_name: "gemini-2.0-flash"


router_agent:
  file_path: "router_agent.log"
  model_name: "gemini-2.0-flash"

orchestrator_agent:
  file_path: "orchestrator_agent.log"
  model_name: "gemini-2.0-flash"